version: '3.7'

services:
    nextjs-front:
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: always
      working_dir: /app
      container_name: nextjs-front
      env_file:
        .env
      command: sh -c 'yarn build && yarn start'
      ports:
        - ${PORT}:${PORT}
      volumes:
        - ./:/app
      networks:
        - frontend


networks:
  frontend:
    driver: bridge